# Rename this to config.yml

# Secret key for securing cookies.
# Generate one with `openssl rand -base64 64`
SECRET_KEY: FOO

# Multiple API keys for notifications
API_KEYS:
  - KEY_ID,VCODE,CHARACTER_ID
# Only one API Key for standings
CONTACT_KEY: KEY_ID,VCODE
API_ROOT: /api
EVE:
  auth_name: J4LP
ADMIN_GROUP: Admin
J4OAUTH:
  consumer_key: FOO
  consumer_secret: BAR
  request_token_params:
    scope: auth_info auth_groups
  base_url: https://j4lp.com/oauth/api/v1/
  request_token_url: None
  access_token_method: GET
  access_token_url: https://j4lp.com/oauth/token
  authorize_url: https://j4lp.com/oauth/authorize